# 开启鼠标支持（支持鼠标点击切换面板，拖动调整大小）
set -g mouse on

# 将终端颜色设置为 256 色，避免 vim/yazi 等工具颜色失真
set -g default-terminal "screen-256color"

# 状态栏美化 (将其移到底部，改变颜色)
set -g status-position bottom
set -g status-bg "#333333"
set -g status-fg white

# 窗口编号从 1 开始 (默认是 0，按键盘不方便)
set -g base-index 1
setw -g pane-base-index 1
